"""v0.2.10

Revision ID: ec3723e4e037
Revises: 8f71a1db97d7
Create Date: 2018-01-23 09:43:24.919194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec3723e4e037'
down_revision = '8f71a1db97d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('air_blguzhang', 'updateTime')
    op.drop_column('air_blguzhang', 'createTime')
    op.drop_column('air_blguzhang_version', 'updateTime')
    op.drop_column('air_blguzhang_version', 'createTime')
    op.drop_column('air_blgz', 'updateTime')
    op.drop_column('air_blgz', 'createTime')
    op.drop_column('air_blgz_version', 'updateTime')
    op.drop_column('air_blgz_version', 'createTime')
    op.drop_column('air_flxgz', 'updateTime')
    op.drop_column('air_flxgz', 'createTime')
    op.alter_column('air_lxgz', 'fileUrl',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.drop_column('air_lxgz', 'updateTime')
    op.drop_column('air_lxgz', 'createTime')
    op.alter_column('air_lxgz_version', 'fileUrl',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True,
               autoincrement=False)
    op.drop_column('air_lxgz_version', 'updateTime')
    op.drop_column('air_lxgz_version', 'createTime')
    op.alter_column('air_material_storage_list', 'engineTime',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('air_material_storage_list', 'flyTime',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('air_material_storage_list_version', 'engineTime',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=255),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('air_material_storage_list_version', 'flyTime',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=255),
               existing_nullable=True,
               autoincrement=False)
    op.add_column('airmaterial_category', sa.Column('isOrNotHaveEffectiveDate', sa.Boolean(), nullable=True))
    op.add_column('airmaterial_category', sa.Column('isOrNotHavePeriodCheck', sa.Boolean(), nullable=True))
    op.add_column('airmaterial_category_version', sa.Column('isOrNotHaveEffectiveDate', sa.Boolean(), autoincrement=False, nullable=True))
    op.add_column('airmaterial_category_version', sa.Column('isOrNotHavePeriodCheck', sa.Boolean(), autoincrement=False, nullable=True))
    op.add_column('assemble_application_list', sa.Column('effectiveDate', sa.String(length=255), nullable=True))
    op.add_column('assemble_application_list', sa.Column('lastCheckDate', sa.String(length=255), nullable=True))
    op.add_column('assemble_application_list', sa.Column('nextCheckDate', sa.String(length=255), nullable=True))
    op.alter_column('assemble_application_list', 'engineTime',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('assemble_application_list', 'flyTime',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_column('assemble_application_list', 'nextCheckTime')
    op.drop_column('assemble_application_list', 'lastCheckTime')
    op.add_column('basic_action', sa.Column('airmaterial_record', sa.Boolean(), nullable=True))
    op.add_column('basic_action', sa.Column('export_pdf', sa.Boolean(), nullable=True))
    op.add_column('basic_action', sa.Column('remove_bound_status', sa.Boolean(), nullable=True))
    op.alter_column('basic_action', 'approve',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'approve_refuse',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'approved',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'borrow_application',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'borrowing_in_return',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'cancel',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'check_complete',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'create',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_as',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_br',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_eo',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_er',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_in',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_lr',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_mr',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_out',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_rf',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_rp_rt',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_rw',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_scrap',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_st',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'delete',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'edit',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'edit_bound_status',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'finish',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'in_store_finish',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'in_store_part',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'out_store_finish',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'out_store_part',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'purchase_application',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'put_in_store',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'receive',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'reserve_again',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'review',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'review_again',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'review_approve',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'review_refuse',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'second_approve_refuse',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'second_approved',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'send',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'sent',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'stored',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'submit',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'submit_review',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'upload_contract_file',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'upload_meeting_file',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'view',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('borrowing_in_return', sa.Column('companyAddr', sa.String(length=255), nullable=True))
    op.add_column('borrowing_in_return', sa.Column('fax', sa.String(length=255), nullable=True))
    op.add_column('borrowing_in_return', sa.Column('mailbox', sa.String(length=255), nullable=True))
    op.add_column('borrowing_in_return', sa.Column('telephone', sa.String(length=255), nullable=True))
    op.add_column('borrowing_in_return_material', sa.Column('effectiveDate', sa.String(length=255), nullable=True))
    op.add_column('borrowing_in_return_material', sa.Column('nextCheckDate', sa.String(length=255), nullable=True))
    op.alter_column('borrowing_in_return_material', 'engineTime',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('borrowing_in_return_material', 'flyTime',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.add_column('borrowing_in_return_version', sa.Column('companyAddr', sa.String(length=255), autoincrement=False, nullable=True))
    op.add_column('borrowing_in_return_version', sa.Column('fax', sa.String(length=255), autoincrement=False, nullable=True))
    op.add_column('borrowing_in_return_version', sa.Column('mailbox', sa.String(length=255), autoincrement=False, nullable=True))
    op.add_column('borrowing_in_return_version', sa.Column('telephone', sa.String(length=255), autoincrement=False, nullable=True))
    op.alter_column('continues', 'relateFileUrl',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.drop_column('continues', 'updateTime')
    op.drop_column('continues', 'createTime')
    op.alter_column('continues_version', 'relateFileUrl',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True,
               autoincrement=False)
    op.drop_column('continues_version', 'updateTime')
    op.drop_column('continues_version', 'createTime')
    op.alter_column('day_record', 'fileResourceUrl',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('day_record_version', 'fileResourceUrl',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True,
               autoincrement=False)
    op.add_column('disassemble_material', sa.Column('effectiveDate', sa.String(length=255), nullable=True))
    op.alter_column('disassemble_material', 'engineTime',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('disassemble_material', 'flyTime',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('examine_repair_record', 'Soluted',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('examine_repair_record', 'repairFileUrl',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.drop_column('examine_repair_record', 'updateTime')
    op.drop_column('examine_repair_record', 'createTime')
    op.alter_column('examine_repair_record_version', 'Soluted',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('examine_repair_record_version', 'repairFileUrl',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True,
               autoincrement=False)
    op.drop_column('examine_repair_record_version', 'updateTime')
    op.drop_column('examine_repair_record_version', 'createTime')
    op.alter_column('fault_reports', 'relateFileUrl',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.drop_column('fault_reports', 'updateTime')
    op.drop_column('fault_reports', 'createTime')
    op.alter_column('fault_reports_version', 'relateFileUrl',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True,
               autoincrement=False)
    op.drop_column('fault_reports_version', 'updateTime')
    op.drop_column('fault_reports_version', 'createTime')
    op.alter_column('file_resource', 'addTime',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('file_resource', 'fileResourceUrl',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.drop_column('file_resource', 'updateTime')
    op.drop_column('file_resource', 'createTime')
    op.alter_column('file_resource_version', 'addTime',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('file_resource_version', 'fileResourceUrl',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True,
               autoincrement=False)
    op.drop_column('file_resource_version', 'updateTime')
    op.drop_column('file_resource_version', 'createTime')
    op.drop_column('flight_log', 'updateTime')
    op.drop_column('flight_log', 'createTime')
    op.drop_column('flight_log_version', 'updateTime')
    op.drop_column('flight_log_version', 'createTime')
    op.alter_column('instruction', 'relateFileUrl',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('instruction_version', 'relateFileUrl',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True,
               autoincrement=False)
    op.add_column('lend_application', sa.Column('contractFile', sa.String(length=1000), nullable=True))
    op.alter_column('lend_application_material', 'engineTime',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('lend_application_material', 'flyTime',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.add_column('lend_application_version', sa.Column('contractFile', sa.String(length=1000), autoincrement=False, nullable=True))
    op.add_column('loan_application', sa.Column('contractFile', sa.String(length=1000), nullable=True))
    op.add_column('loan_application', sa.Column('fax', sa.String(length=255), nullable=True))
    op.add_column('loan_application', sa.Column('mailbox', sa.String(length=255), nullable=True))
    op.add_column('loan_application', sa.Column('telephone', sa.String(length=255), nullable=True))
    op.add_column('loan_application_version', sa.Column('contractFile', sa.String(length=1000), autoincrement=False, nullable=True))
    op.add_column('loan_application_version', sa.Column('fax', sa.String(length=255), autoincrement=False, nullable=True))
    op.add_column('loan_application_version', sa.Column('mailbox', sa.String(length=255), autoincrement=False, nullable=True))
    op.add_column('loan_application_version', sa.Column('telephone', sa.String(length=255), autoincrement=False, nullable=True))
    op.add_column('loan_material', sa.Column('effectiveDate', sa.String(length=255), nullable=True))
    op.alter_column('loan_material', 'engineTime',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('loan_material', 'flyTime',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.add_column('loan_return_order', sa.Column('fax', sa.String(length=255), nullable=True))
    op.add_column('loan_return_order', sa.Column('mailbox', sa.String(length=255), nullable=True))
    op.add_column('loan_return_order', sa.Column('telephone', sa.String(length=255), nullable=True))
    op.add_column('loan_return_order_version', sa.Column('fax', sa.String(length=255), autoincrement=False, nullable=True))
    op.add_column('loan_return_order_version', sa.Column('mailbox', sa.String(length=255), autoincrement=False, nullable=True))
    op.add_column('loan_return_order_version', sa.Column('telephone', sa.String(length=255), autoincrement=False, nullable=True))
    op.drop_column('maintenance_plan', 'updateTime')
    op.drop_column('maintenance_plan', 'createTime')
    op.drop_column('maintenance_status', 'updateTime')
    op.drop_column('maintenance_status', 'createTime')
    op.alter_column('manufacturer', 'fileResourceUrl',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('manufacturer_version', 'fileResourceUrl',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True,
               autoincrement=False)
    op.drop_column('plan_fault_statistical', 'updateTime')
    op.drop_column('plan_fault_statistical', 'createTime')
    op.add_column('put_out_store', sa.Column('accessory', sa.String(length=1000), nullable=True))
    op.add_column('put_out_store', sa.Column('companyAddr', sa.String(length=255), nullable=True))
    op.add_column('put_out_store', sa.Column('contactPerson', sa.String(length=255), nullable=True))
    op.add_column('put_out_store', sa.Column('fax', sa.String(length=255), nullable=True))
    op.add_column('put_out_store', sa.Column('mailbox', sa.String(length=255), nullable=True))
    op.add_column('put_out_store', sa.Column('telephone', sa.String(length=255), nullable=True))
    op.add_column('put_out_store_material', sa.Column('effectiveDate', sa.String(length=255), nullable=True))
    op.alter_column('put_out_store_material', 'engineTime',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('put_out_store_material', 'flyTime',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.add_column('put_out_store_version', sa.Column('accessory', sa.String(length=1000), autoincrement=False, nullable=True))
    op.add_column('put_out_store_version', sa.Column('companyAddr', sa.String(length=255), autoincrement=False, nullable=True))
    op.add_column('put_out_store_version', sa.Column('contactPerson', sa.String(length=255), autoincrement=False, nullable=True))
    op.add_column('put_out_store_version', sa.Column('fax', sa.String(length=255), autoincrement=False, nullable=True))
    op.add_column('put_out_store_version', sa.Column('mailbox', sa.String(length=255), autoincrement=False, nullable=True))
    op.add_column('put_out_store_version', sa.Column('telephone', sa.String(length=255), autoincrement=False, nullable=True))
    op.add_column('put_storage', sa.Column('accessory', sa.String(length=1000), nullable=True))
    op.add_column('put_storage_version', sa.Column('accessory', sa.String(length=1000), autoincrement=False, nullable=True))
    op.add_column('repair_material', sa.Column('effectiveDate', sa.String(length=255), nullable=True))
    op.add_column('repair_material', sa.Column('lastCheckDate', sa.String(length=255), nullable=True))
    op.add_column('repair_material', sa.Column('nextCheckDate', sa.String(length=255), nullable=True))
    op.alter_column('repair_material', 'engineTime',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('repair_material', 'flyTime',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('repair_return_material', 'engineTime',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('repair_return_material', 'flyTime',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('repair_supplier', 'fileResourceUrl',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('repair_supplier_version', 'fileResourceUrl',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True,
               autoincrement=False)
    op.add_column('scrap_material', sa.Column('effectiveDate', sa.String(length=255), nullable=True))
    op.add_column('scrap_material', sa.Column('lastCheckDate', sa.String(length=255), nullable=True))
    op.add_column('scrap_material', sa.Column('nextCheckDate', sa.String(length=255), nullable=True))
    op.drop_column('shengchanzl', 'updateTime')
    op.drop_column('shengchanzl', 'createTime')
    op.drop_column('shengchanzl_version', 'updateTime')
    op.drop_column('shengchanzl_version', 'createTime')
    op.alter_column('storage_list', 'engineTime',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('storage_list', 'flyTime',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('supplier', 'fileResourceUrl',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('supplier_version', 'fileResourceUrl',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('train_file_resource', 'trainFileResourceUrl',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.drop_column('train_file_resource', 'updateTime')
    op.drop_column('train_file_resource', 'createTime')
    op.alter_column('train_file_resource_version', 'trainFileResourceUrl',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True,
               autoincrement=False)
    op.drop_column('train_file_resource_version', 'updateTime')
    op.drop_column('train_file_resource_version', 'createTime')
    op.alter_column('train_plan', 'trainPlanFileUrl',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.drop_column('train_plan', 'updateTime')
    op.drop_column('train_plan', 'createTime')
    op.alter_column('train_plan_version', 'trainPlanFileUrl',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True,
               autoincrement=False)
    op.drop_column('train_plan_version', 'updateTime')
    op.drop_column('train_plan_version', 'createTime')
    op.drop_column('train_record', 'updateUser')
    op.drop_column('train_record', 'updTime')
    op.drop_column('train_record', 'updateTime')
    op.drop_column('train_record', 'addTime')
    op.drop_column('train_record', 'submitTime')
    op.drop_column('train_record', 'submitUser')
    op.drop_column('train_record', 'createUser')
    op.drop_column('train_record', 'createTime')
    op.drop_column('train_record_version', 'updateUser')
    op.drop_column('train_record_version', 'updTime')
    op.drop_column('train_record_version', 'updateTime')
    op.drop_column('train_record_version', 'addTime')
    op.drop_column('train_record_version', 'submitTime')
    op.drop_column('train_record_version', 'submitUser')
    op.drop_column('train_record_version', 'createUser')
    op.drop_column('train_record_version', 'createTime')
    op.alter_column('trouble_shooting', 'shootingFileUrl',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.drop_column('trouble_shooting', 'updateTime')
    op.drop_column('trouble_shooting', 'createTime')
    op.alter_column('trouble_shooting_version', 'shootingFileUrl',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True,
               autoincrement=False)
    op.drop_column('trouble_shooting_version', 'updateTime')
    op.drop_column('trouble_shooting_version', 'createTime')
    op.alter_column('user', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'active',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.add_column('trouble_shooting_version', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('trouble_shooting_version', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.alter_column('trouble_shooting_version', 'shootingFileUrl',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True,
               autoincrement=False)
    op.add_column('trouble_shooting', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('trouble_shooting', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.alter_column('trouble_shooting', 'shootingFileUrl',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.add_column('train_record_version', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_record_version', sa.Column('createUser', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('train_record_version', sa.Column('submitUser', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('train_record_version', sa.Column('submitTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_record_version', sa.Column('addTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_record_version', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_record_version', sa.Column('updTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_record_version', sa.Column('updateUser', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('train_record', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_record', sa.Column('createUser', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('train_record', sa.Column('submitUser', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('train_record', sa.Column('submitTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_record', sa.Column('addTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_record', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_record', sa.Column('updTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_record', sa.Column('updateUser', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('train_plan_version', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_plan_version', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.alter_column('train_plan_version', 'trainPlanFileUrl',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True,
               autoincrement=False)
    op.add_column('train_plan', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_plan', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.alter_column('train_plan', 'trainPlanFileUrl',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.add_column('train_file_resource_version', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_file_resource_version', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.alter_column('train_file_resource_version', 'trainFileResourceUrl',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True,
               autoincrement=False)
    op.add_column('train_file_resource', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_file_resource', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.alter_column('train_file_resource', 'trainFileResourceUrl',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('supplier_version', 'fileResourceUrl',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('supplier', 'fileResourceUrl',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('storage_list', 'flyTime',
               existing_type=sa.String(length=255),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('storage_list', 'engineTime',
               existing_type=sa.String(length=255),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.add_column('shengchanzl_version', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('shengchanzl_version', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('shengchanzl', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('shengchanzl', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.drop_column('scrap_material', 'nextCheckDate')
    op.drop_column('scrap_material', 'lastCheckDate')
    op.drop_column('scrap_material', 'effectiveDate')
    op.alter_column('repair_supplier_version', 'fileResourceUrl',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('repair_supplier', 'fileResourceUrl',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('repair_return_material', 'flyTime',
               existing_type=sa.String(length=255),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('repair_return_material', 'engineTime',
               existing_type=sa.String(length=255),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('repair_material', 'flyTime',
               existing_type=sa.String(length=255),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('repair_material', 'engineTime',
               existing_type=sa.String(length=255),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.drop_column('repair_material', 'nextCheckDate')
    op.drop_column('repair_material', 'lastCheckDate')
    op.drop_column('repair_material', 'effectiveDate')
    op.drop_column('put_storage_version', 'accessory')
    op.drop_column('put_storage', 'accessory')
    op.drop_column('put_out_store_version', 'telephone')
    op.drop_column('put_out_store_version', 'mailbox')
    op.drop_column('put_out_store_version', 'fax')
    op.drop_column('put_out_store_version', 'contactPerson')
    op.drop_column('put_out_store_version', 'companyAddr')
    op.drop_column('put_out_store_version', 'accessory')
    op.alter_column('put_out_store_material', 'flyTime',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('put_out_store_material', 'engineTime',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.drop_column('put_out_store_material', 'effectiveDate')
    op.drop_column('put_out_store', 'telephone')
    op.drop_column('put_out_store', 'mailbox')
    op.drop_column('put_out_store', 'fax')
    op.drop_column('put_out_store', 'contactPerson')
    op.drop_column('put_out_store', 'companyAddr')
    op.drop_column('put_out_store', 'accessory')
    op.add_column('plan_fault_statistical', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('plan_fault_statistical', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.alter_column('manufacturer_version', 'fileResourceUrl',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('manufacturer', 'fileResourceUrl',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.add_column('maintenance_status', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('maintenance_status', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('maintenance_plan', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('maintenance_plan', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.drop_column('loan_return_order_version', 'telephone')
    op.drop_column('loan_return_order_version', 'mailbox')
    op.drop_column('loan_return_order_version', 'fax')
    op.drop_column('loan_return_order', 'telephone')
    op.drop_column('loan_return_order', 'mailbox')
    op.drop_column('loan_return_order', 'fax')
    op.alter_column('loan_material', 'flyTime',
               existing_type=sa.String(length=255),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('loan_material', 'engineTime',
               existing_type=sa.String(length=255),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.drop_column('loan_material', 'effectiveDate')
    op.drop_column('loan_application_version', 'telephone')
    op.drop_column('loan_application_version', 'mailbox')
    op.drop_column('loan_application_version', 'fax')
    op.drop_column('loan_application_version', 'contractFile')
    op.drop_column('loan_application', 'telephone')
    op.drop_column('loan_application', 'mailbox')
    op.drop_column('loan_application', 'fax')
    op.drop_column('loan_application', 'contractFile')
    op.drop_column('lend_application_version', 'contractFile')
    op.alter_column('lend_application_material', 'flyTime',
               existing_type=sa.String(length=255),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('lend_application_material', 'engineTime',
               existing_type=sa.String(length=255),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.drop_column('lend_application', 'contractFile')
    op.alter_column('instruction_version', 'relateFileUrl',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('instruction', 'relateFileUrl',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.add_column('flight_log_version', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('flight_log_version', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('flight_log', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('flight_log', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('file_resource_version', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('file_resource_version', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.alter_column('file_resource_version', 'fileResourceUrl',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('file_resource_version', 'addTime',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               autoincrement=False)
    op.add_column('file_resource', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('file_resource', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.alter_column('file_resource', 'fileResourceUrl',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('file_resource', 'addTime',
               existing_type=sa.TIMESTAMP(timezone=True),
               server_default=sa.text(u'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('fault_reports_version', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('fault_reports_version', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.alter_column('fault_reports_version', 'relateFileUrl',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True,
               autoincrement=False)
    op.add_column('fault_reports', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('fault_reports', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.alter_column('fault_reports', 'relateFileUrl',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.add_column('examine_repair_record_version', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('examine_repair_record_version', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.alter_column('examine_repair_record_version', 'repairFileUrl',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('examine_repair_record_version', 'Soluted',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True,
               autoincrement=False)
    op.add_column('examine_repair_record', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('examine_repair_record', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.alter_column('examine_repair_record', 'repairFileUrl',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('examine_repair_record', 'Soluted',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('disassemble_material', 'flyTime',
               existing_type=sa.String(length=255),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('disassemble_material', 'engineTime',
               existing_type=sa.String(length=255),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.drop_column('disassemble_material', 'effectiveDate')
    op.alter_column('day_record_version', 'fileResourceUrl',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('day_record', 'fileResourceUrl',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.add_column('continues_version', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('continues_version', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.alter_column('continues_version', 'relateFileUrl',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True,
               autoincrement=False)
    op.add_column('continues', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('continues', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.alter_column('continues', 'relateFileUrl',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('borrowing_in_return_version', 'telephone')
    op.drop_column('borrowing_in_return_version', 'mailbox')
    op.drop_column('borrowing_in_return_version', 'fax')
    op.drop_column('borrowing_in_return_version', 'companyAddr')
    op.alter_column('borrowing_in_return_material', 'flyTime',
               existing_type=sa.String(length=255),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('borrowing_in_return_material', 'engineTime',
               existing_type=sa.String(length=255),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.drop_column('borrowing_in_return_material', 'nextCheckDate')
    op.drop_column('borrowing_in_return_material', 'effectiveDate')
    op.drop_column('borrowing_in_return', 'telephone')
    op.drop_column('borrowing_in_return', 'mailbox')
    op.drop_column('borrowing_in_return', 'fax')
    op.drop_column('borrowing_in_return', 'companyAddr')
    op.alter_column('basic_action', 'view',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'upload_meeting_file',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'upload_contract_file',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'submit_review',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'submit',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'stored',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'sent',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'send',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'second_approved',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'second_approve_refuse',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'review_refuse',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'review_approve',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'review_again',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'review',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'reserve_again',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'receive',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'put_in_store',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'purchase_application',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'out_store_part',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'out_store_finish',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'in_store_part',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'in_store_finish',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'finish',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'edit_bound_status',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'edit',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'delete',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_st',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_scrap',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_rw',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_rp_rt',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_rf',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_out',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_mr',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_lr',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_in',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_er',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_eo',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_br',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_as',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'create',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'check_complete',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'cancel',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'borrowing_in_return',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'borrow_application',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'approved',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'approve_refuse',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'approve',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('basic_action', 'remove_bound_status')
    op.drop_column('basic_action', 'export_pdf')
    op.drop_column('basic_action', 'airmaterial_record')
    op.add_column('assemble_application_list', sa.Column('lastCheckTime', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('assemble_application_list', sa.Column('nextCheckTime', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('assemble_application_list', 'flyTime',
               existing_type=sa.String(length=255),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('assemble_application_list', 'engineTime',
               existing_type=sa.String(length=255),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.drop_column('assemble_application_list', 'nextCheckDate')
    op.drop_column('assemble_application_list', 'lastCheckDate')
    op.drop_column('assemble_application_list', 'effectiveDate')
    op.drop_column('airmaterial_category_version', 'isOrNotHavePeriodCheck')
    op.drop_column('airmaterial_category_version', 'isOrNotHaveEffectiveDate')
    op.drop_column('airmaterial_category', 'isOrNotHavePeriodCheck')
    op.drop_column('airmaterial_category', 'isOrNotHaveEffectiveDate')
    op.alter_column('air_material_storage_list_version', 'flyTime',
               existing_type=sa.String(length=255),
               type_=mysql.FLOAT(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('air_material_storage_list_version', 'engineTime',
               existing_type=sa.String(length=255),
               type_=mysql.FLOAT(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('air_material_storage_list', 'flyTime',
               existing_type=sa.String(length=255),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('air_material_storage_list', 'engineTime',
               existing_type=sa.String(length=255),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.add_column('air_lxgz_version', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('air_lxgz_version', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.alter_column('air_lxgz_version', 'fileUrl',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True,
               autoincrement=False)
    op.add_column('air_lxgz', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('air_lxgz', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.alter_column('air_lxgz', 'fileUrl',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.add_column('air_flxgz', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('air_flxgz', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('air_blgz_version', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('air_blgz_version', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('air_blgz', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('air_blgz', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('air_blguzhang_version', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('air_blguzhang_version', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('air_blguzhang', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('air_blguzhang', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
