"""v0.1.20

Revision ID: 53fbf689a55a
Revises: 37f589091066
Create Date: 2017-11-29 09:55:36.868806

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53fbf689a55a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('lend_application', 'accessory',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('lend_application_version', 'accessory',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)

    op.alter_column('purchase_application', 'accessory',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('purchase_application_version', 'accessory',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('purchase_application', 'contractFile',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('purchase_application_version', 'contractFile',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('purchase_application', 'meetingFile',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('purchase_application_version', 'meetingFile',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('repair_application', 'accessory',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('repair_application_version', 'accessory',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('repair_application', 'contractFile',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('repair_application_version', 'contractFile',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('lend_application', 'accessory',
               type_=mysql.VARCHAR(length=255),
               existing_type=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('lend_application_version', 'accessory',
               type_=mysql.VARCHAR(length=255),
               existing_type=sa.String(length=1000),
               existing_nullable=True)

    op.alter_column('purchase_application', 'accessory',
               type_=mysql.VARCHAR(length=255),
               existing_type=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('purchase_application_version', 'accessory',
               type_=mysql.VARCHAR(length=255),
               existing_type=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('purchase_application', 'contractFile',
               type_=mysql.VARCHAR(length=255),
               existing_type=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('purchase_application_version', 'contractFile',
               type_=mysql.VARCHAR(length=255),
               existing_type=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('purchase_application', 'meetingFile',
               type_=mysql.VARCHAR(length=255),
               existing_type=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('purchase_application_version', 'meetingFile',
               type_=mysql.VARCHAR(length=255),
               existing_type=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('repair_application', 'accessory',
               type_=mysql.VARCHAR(length=255),
               existing_type=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('repair_application_version', 'accessory',
               type_=mysql.VARCHAR(length=255),
               existing_type=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('repair_application', 'contractFile',
               type_=mysql.VARCHAR(length=255),
               existing_type=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('repair_application_version', 'contractFile',
               type_=mysql.VARCHAR(length=255),
               existing_type=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###
