# coding: utf-8

from __future__ import unicode_literals


column_labels = {
    'id': '编号',
    'name': '名称',
    'planeType': '机型',
    'sn': '飞行器串号',
    'importedDate': '引进日期',
    'manufacture': '制造商',
    'acn': '适航证编号',
    'sln': '电台执照编号',
    'nrn': '国籍登记证编号',
    'manufactureDate': '执照日期',
    'permanentAirport': '常驻机场',
    'flightTime': '托管前飞行时间',
    'landTimes': '托管前起落次数',
    'remark': '备注',
    'imageUrl': '飞机图片',
    'engineNumber': '发动机序号',
    'acnDeadline': '适航证编号到期时间',
    'slnDeadline': '国籍登记编号到期时间',
    'nrnDeadline': '电台执照编号到期时间',
    'aircraftId': '飞行器注册号',
    'departureAirport': '起飞机场',
    'landingAirport': '降落机场',
    'flightDate': '飞行日期',
    'captain': '正驾驶',
    'copilot': '副驾驶',
    'crew': '机组',
    'passengers': '其他人员',
    'departureTime': '开车时间',
    'landingTime': '关车时间',
    'flightTime': '飞行小时',
    'landings': '起落次数',
    'remark': '备注',
    'logTime': '日志录入时间',
    'aircraftType': '机型信息',
    'operation': '操作',
    'type': '类型',
    'description': '描述信息',
    'completeDate': '完成日期',
    'generateTime': '生成时间',
    'mxId': '维修方案编号',
    'warningLevel': '预警等级',
    'best': '预计检查日期',
    'error': '错误提示',
    'leftHour': '剩余小时',
    'leftTimes': '剩余次数',
    'leftDay': '剩余天',
    'leftEngineTime': '剩余发动机时间',
    'checkbox': "",
    'totalHours': '总飞行时间',
    'totalTimes': '总起降次数',
    'boundedMxp': '绑定的维修方案',
    'engineTime': '发动机时间',
    'missionType': '任务类型',
    'flyProperty': '飞行性质',
    'medicinePrescription': '药品配方',
    'workAcres': '作业亩数',
    'poweronTime': '开车时间',
    'skidoffTime': '滑出时间',
    'powerdownTime': '关车时间',
    'stopTime': '停止时间',
    'workArea': '作业区域',
    'formMaker': '制单人',
    'formmakeTime': '制单时间',
    'modifier': '修改人',
    'modifyTime': '修改时间',
    'submitter': '提交人',
    'submitTime': '提交时间',
    'earliest': '预计检查日期',
    'return': '返回',
    'pn': '件号',
    'serialNumber': '序号',
}
