"""5b3b031_20

Revision ID: bba61a45dbe8
Revises: 4bf36f32bbea
Create Date: 2018-01-09 19:48:32.288053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bba61a45dbe8'
down_revision = '4bf36f32bbea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('air_blguzhang', 'updateTime')
    op.drop_column('air_blguzhang', 'createTime')
    op.drop_column('air_blguzhang_version', 'updateTime')
    op.drop_column('air_blguzhang_version', 'createTime')
    op.drop_column('air_blgz', 'updateTime')
    op.drop_column('air_blgz', 'createTime')
    op.drop_column('air_blgz_version', 'updateTime')
    op.drop_column('air_blgz_version', 'createTime')
    op.drop_column('air_flxgz', 'updateTime')
    op.drop_column('air_flxgz', 'createTime')
    op.drop_column('air_lxgz', 'updateTime')
    op.drop_column('air_lxgz', 'createTime')
    op.drop_column('air_lxgz_version', 'updateTime')
    op.drop_column('air_lxgz_version', 'createTime')
    op.alter_column('airmaterial_category', 'isOrNotHaveEffectiveDate',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('airmaterial_category', 'isOrNotHavePeriodCheck',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('airmaterial_category_version', 'isOrNotHaveEffectiveDate',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('airmaterial_category_version', 'isOrNotHavePeriodCheck',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('basic_action', 'approve',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'approve_refuse',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'approved',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'borrow_application',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'borrowing_in_return',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'cancel',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'check_complete',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'create',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_as',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_br',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_eo',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_er',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_in',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_lr',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_mr',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_out',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_rf',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_rp_rt',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_rw',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_scrap',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_st',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'delete',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'edit',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'edit_bound_status',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'export_pdf',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'finish',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'in_store_finish',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'in_store_part',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'out_store_finish',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'out_store_part',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'purchase_application',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'put_in_store',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'receive',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'remove_bound_status',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'reserve_again',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'review',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'review_again',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'review_approve',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'review_refuse',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'second_approve_refuse',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'second_approved',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'send',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'sent',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'stored',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'submit',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'submit_review',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'upload_contract_file',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'upload_meeting_file',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('basic_action', 'view',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.drop_column('continues', 'updateTime')
    op.drop_column('continues', 'createTime')
    op.drop_column('continues_version', 'updateTime')
    op.drop_column('continues_version', 'createTime')
    op.alter_column('examine_repair_record', 'Soluted',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.drop_column('examine_repair_record', 'updateTime')
    op.drop_column('examine_repair_record', 'createTime')
    op.alter_column('examine_repair_record_version', 'Soluted',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True,
               autoincrement=False)
    op.drop_column('examine_repair_record_version', 'updateTime')
    op.drop_column('examine_repair_record_version', 'createTime')
    op.drop_column('fault_reports', 'updateTime')
    op.drop_column('fault_reports', 'createTime')
    op.drop_column('fault_reports_version', 'updateTime')
    op.drop_column('fault_reports_version', 'createTime')
    op.alter_column('file_resource', 'addTime',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('file_resource', 'updateTime')
    op.drop_column('file_resource', 'createTime')
    op.alter_column('file_resource_version', 'addTime',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True,
               autoincrement=False)
    op.drop_column('file_resource_version', 'updateTime')
    op.drop_column('file_resource_version', 'createTime')
    op.drop_column('flight_log', 'updateTime')
    op.drop_column('flight_log', 'createTime')
    op.drop_column('flight_log_version', 'updateTime')
    op.drop_column('flight_log_version', 'createTime')
    op.drop_column('maintenance_plan', 'updateTime')
    op.drop_column('maintenance_plan', 'createTime')
    op.drop_column('maintenance_status', 'updateTime')
    op.drop_column('maintenance_status', 'createTime')
    op.drop_column('plan_fault_statistical', 'updateTime')
    op.drop_column('plan_fault_statistical', 'createTime')
    op.drop_column('shengchanzl', 'updateTime')
    op.drop_column('shengchanzl', 'createTime')
    op.drop_column('shengchanzl_version', 'updateTime')
    op.drop_column('shengchanzl_version', 'createTime')
    op.drop_column('train_file_resource', 'updateTime')
    op.drop_column('train_file_resource', 'createTime')
    op.drop_column('train_file_resource_version', 'updateTime')
    op.drop_column('train_file_resource_version', 'createTime')
    op.drop_column('train_plan', 'updateTime')
    op.drop_column('train_plan', 'createTime')
    op.drop_column('train_plan_version', 'updateTime')
    op.drop_column('train_plan_version', 'createTime')
    op.drop_column('train_record', 'updateUser')
    op.drop_column('train_record', 'updTime')
    op.drop_column('train_record', 'updateTime')
    op.drop_column('train_record', 'addTime')
    op.drop_column('train_record', 'submitTime')
    op.drop_column('train_record', 'submitUser')
    op.drop_column('train_record', 'createUser')
    op.drop_column('train_record', 'createTime')
    op.drop_column('train_record_version', 'updateUser')
    op.drop_column('train_record_version', 'updTime')
    op.drop_column('train_record_version', 'updateTime')
    op.drop_column('train_record_version', 'addTime')
    op.drop_column('train_record_version', 'submitTime')
    op.drop_column('train_record_version', 'submitUser')
    op.drop_column('train_record_version', 'createUser')
    op.drop_column('train_record_version', 'createTime')
    op.drop_column('trouble_shooting', 'updateTime')
    op.drop_column('trouble_shooting', 'createTime')
    op.drop_column('trouble_shooting_version', 'updateTime')
    op.drop_column('trouble_shooting_version', 'createTime')
    op.alter_column('user', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'active',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.add_column('trouble_shooting_version', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('trouble_shooting_version', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('trouble_shooting', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('trouble_shooting', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_record_version', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_record_version', sa.Column('createUser', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('train_record_version', sa.Column('submitUser', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('train_record_version', sa.Column('submitTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_record_version', sa.Column('addTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_record_version', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_record_version', sa.Column('updTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_record_version', sa.Column('updateUser', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('train_record', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_record', sa.Column('createUser', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('train_record', sa.Column('submitUser', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('train_record', sa.Column('submitTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_record', sa.Column('addTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_record', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_record', sa.Column('updTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_record', sa.Column('updateUser', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('train_plan_version', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_plan_version', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_plan', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_plan', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_file_resource_version', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_file_resource_version', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_file_resource', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('train_file_resource', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('shengchanzl_version', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('shengchanzl_version', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('shengchanzl', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('shengchanzl', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('plan_fault_statistical', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('plan_fault_statistical', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('maintenance_status', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('maintenance_status', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('maintenance_plan', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('maintenance_plan', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('flight_log_version', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('flight_log_version', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('flight_log', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('flight_log', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('file_resource_version', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('file_resource_version', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.alter_column('file_resource_version', 'addTime',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               autoincrement=False)
    op.add_column('file_resource', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('file_resource', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.alter_column('file_resource', 'addTime',
               existing_type=sa.TIMESTAMP(timezone=True),
               server_default=sa.text(u'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('fault_reports_version', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('fault_reports_version', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('fault_reports', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('fault_reports', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('examine_repair_record_version', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('examine_repair_record_version', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.alter_column('examine_repair_record_version', 'Soluted',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True,
               autoincrement=False)
    op.add_column('examine_repair_record', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('examine_repair_record', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.alter_column('examine_repair_record', 'Soluted',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.add_column('continues_version', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('continues_version', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('continues', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('continues', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.alter_column('basic_action', 'view',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'upload_meeting_file',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'upload_contract_file',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'submit_review',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'submit',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'stored',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'sent',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'send',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'second_approved',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'second_approve_refuse',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'review_refuse',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'review_approve',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'review_again',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'review',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'reserve_again',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'remove_bound_status',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'receive',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'put_in_store',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'purchase_application',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'out_store_part',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'out_store_finish',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'in_store_part',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'in_store_finish',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'finish',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'export_pdf',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'edit_bound_status',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'edit',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'delete',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_st',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_scrap',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_rw',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_rp_rt',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_rf',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_out',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_mr',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_lr',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_in',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_er',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_eo',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_br',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'create_as',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'create',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'check_complete',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'cancel',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'borrowing_in_return',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'borrow_application',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'approved',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'approve_refuse',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('basic_action', 'approve',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('airmaterial_category_version', 'isOrNotHavePeriodCheck',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('airmaterial_category_version', 'isOrNotHaveEffectiveDate',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('airmaterial_category', 'isOrNotHavePeriodCheck',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('airmaterial_category', 'isOrNotHaveEffectiveDate',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.add_column('air_lxgz_version', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('air_lxgz_version', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('air_lxgz', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('air_lxgz', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('air_flxgz', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('air_flxgz', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('air_blgz_version', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('air_blgz_version', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('air_blgz', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('air_blgz', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('air_blguzhang_version', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('air_blguzhang_version', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('air_blguzhang', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('air_blguzhang', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
