# coding: utf-8

from __future__ import unicode_literals


all_labels = {
    'model': '关联模型',
    'create': '新建',
    'edit': '编辑',
    'view': '查看',
    'delete': '删除',
    'submit_review': '提交复核',
    'review_approve': '复核确认',
    'review_refuse': '复核拒绝',
    'review_again': '提交再次复核',
    'approved': '批准确认',
    'approve_refuse': '批准拒绝',
    'cancel': '撤销',
    'finish': '完成',
    'edit_bound_status': '编辑绑定状态',
    'remove_bound_status': '解除绑定状态',
    'second_approved': '二级审批',
    'second_approve_refuse': '二级审批拒绝',
    'review': '复核',
    'approve': '审批',
    'submit': '提交',
    'send': '发送',
    'create_eo': '新建工程指令',
    'sent': '下发',
    'receive': '接收',
    'create_st': '制定排故方案',
    'create_er': '新建排故检修',
    'create_rw': '新建例行工作',
    'create_rf': '新建保留故障',
    'reserve_again': '继续保留',
    'put_in_store': '准备入库',
    'stored': '入库完成',
    'create_mr': '新建维护保养记录',
    'upload_contract_file': '上传合同文件',
    'upload_meeting_file': '上传会议纪要',
    'borrowing_in_return': '借入归还',
    'put_out_store': '出库',
    'create_in': '准备入库',
    'create_out': '准备出库',
    'create_br': '借入归还',
    'create_lr': '借出归还',
    'create_as': '准备装机',
    'create_rp_rt': '新建送修归还单',
    'check_complete': '检查完成',
    'purchase_application': '采购',
    'borrow_application': '借入',
    'create_scrap': '新建报废',
    'in_store_part': '部分入库',
    'in_store_finish': '全部入库',
    'out_store_part': '部分出库',
    'out_store_finish': '出库完成',
    'export_pdf': '打印',
    'airmaterial_record': '履历'
}
